# Generated by Django 6.0.7 on 2026-07-22 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=200)),
                ('rfc', models.CharField(max_length=15, unique=True)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('marcas', models.JSONField(default=list)),
                ('horarios', models.JSONField(default=list)),
                ('ofrece_remolque', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
